M48
; DRILL file {KiCad 8.0.4} date 2024-11-05T13:41:38+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-05T13:41:38+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X2.4Y30.1
X2.45Y2.51
X33.3Y30.0
X33.3Y2.5
T2
X54.13Y30.46
M30
