% ElectronEmissionCurrentEstimation.m
% This script estimates the current generated by electron emission
% through thermionic emission within a vacuum chamber.

% Physical Constants
k = 8.617e-5; % Boltzmann constant (eV/K)
A_Richardson = 120; % Richardson constant (A/cm^2/K^2) for tungsten
phi = 4.5; % Work function of tungsten (eV)
e = 1.6e-19; % Elementary charge (C)
m = 9.11e-31; % Electron mass (kg)
epsilon_0 = 8.85e-12; % Vacuum permittivity (F/m)

% Experimental Parameters
T = 2500; % Temperature of the cathode (K)
Vs = 6; % Voltage applied to the cathode (V)
Vp = 60; % Voltage applied to the anode (V)
Vg = 12000; % Voltage applied to the grid (V)
dg = 0.01; % Distance from the grid to the anode (m), from 0 to d
d = 0.05; % Distance between cathode and anode (m)
p_torr=1e-5; % Pressure in the vacuum chamber (Torr)
p = p_torr*133.3; % Pressure in the vacuum chamber (Pa)
D = 0.0005; % Diameter of the tungsten filament (m)
L = 0.5; % Length of the tungsten filament (m)

% Calculate the surface area of the cathode
A_cathode = pi * D * L; % Surface area of the cylindrical filament (m^2)

% Richardson-Dushman equation for thermionic emission current density
% without field assisted emission
J_th = A_Richardson * T^2 * exp(-phi / (k * T)); % Current density (A/m^2)

% Richardson-Dushman equation for thermionic emission current density
% with field assisted emission
E=(Vg-Vs)/(d-dg)+(Vp-Vs)/d;
delta_phi=sqrt(e*E/(4*pi*epsilon_0));
J = A_Richardson * T^2 * exp(-(phi-delta_phi) / (k * T)); % Current density (A/m^2)

% Total emitted current
I_emission = J * A_cathode; % Current emitted by thermionic emission (A)

% Child-Langmuir law for space-charge limited current
I_space_charge = (4 * epsilon_0 / 9) * sqrt(2 * e / m) * A_cathode * ((Vp-Vs)^(3/2) / d^2+(Vg-Vs)^(3/2) / (d-dg)^2);

% Mean free path of electrons (considering collisions with gas molecules)
sigma = 1e-19; % Estimated collision cross-section (m^2)
mean_free_path = (k * T) / (sqrt(2) * pi * sigma * p);

% Effective current considering collisions
collision_factor = exp(-d / mean_free_path);
I_effective = min(I_emission, I_space_charge) * collision_factor;

% Display results
fprintf('Thermionic Emission Current: %.3e A\n', I_emission);
fprintf('Space-Charge Limited Current: %.3e A\n', I_space_charge);
fprintf('Effective Current Considering Collisions: %.3e A\n', I_effective);

